### ISSUE TITLE
no exit from the main flow of the app

### ISSUE THREAD

**Issue by Yousef-Majidi** [rabroldan/Waypoint#5]
Searching through the code, I did not see a specific key input (ex. 'q') to exit the app at any point during the loop. 
The features you have for creating a file right from the app when a file doesn't exist is a nice touch, but it would help to be able to exit this process at any time as well. 

Pressing 'q' and ctrl + c both do exit the flow, but they also throw an exception which you might want to at least handle so it doesn't pop up.

**Comment by Yousef-Majidi** [comment]
quick note here. I ran the program with a file that doesn't exist. It triggered the process to create the file. I indicated the file name as 'test.txt', but before the process finished, I exited the app. This caused a broken file to be created in the root directory without an extension. The name of the file was 'test', but it did not have any extensions. Not sure what the bug is here, but perhaps a solution would be to not actually create the file until the process is fully complete

**Comment by rabroldan** [comment]
exit program has been added
