### ISSUE TITLE
issues with processing a directory

### ISSUE THREAD

**Issue by Yousef-Majidi** [rabroldan/Waypoint#7]
As per [release 0.1](https://github.com/Seneca-CDOT/topics-in-open-source-2023/wiki/release-0.1) instructions:
`If the input is a .txt file, it should process that file; if it's a directory, your tool should look for and find all .txt files within that folder, processing each one.`

When a directory is specified, the program should automatically look for any .txt files in that directory and run the process. I realize that might be slightly different based on how you've designed your application. But the instructions on how to process files in a directory are slightly vague. See the image below:
![image](https://github.com/rabroldan/Waypoint/assets/28239685/8bbae024-3f81-44be-8e4e-b530df72a773)

Notice that I have two files in directory `input`. I specify this directory for the app, but the word input prints one letter at a time on a new line. When asked which file do you want to open, I assumed I should provide the name of the file, but I got the result that you see.

**Comment by rabroldan** [comment]
directory has been updated and folders are now being processed properly
